### ISSUE TITLE
mpg321 support

### ISSUE THREAD

**Issue by miguelmota** [uschek/somafm#8]
Needs support for `mpg321` player

**Comment by uschek** [comment]
@miguelmota Thanks for the suggestion and PR!

Is there any way to make mpg321 show song titles? Because this application is all about a nice UI. It would be confusing if nothing is printed and we would have to implement some edge cases (copy song title to clipboard, don't update window title, show playing indicator, …).

I noticed mpg123 prints song titles. We could think about adding that if needed. Is there a specific reason you don't use mpg123, MPlayer or mpv?

**Comment by miguelmota** [comment]
@uschek Good point

Using `mpg321` is just kind of an old habit. Will use `mpv`

Thanks!

**Comment by Rishab-Honeywell** [comment]
Can we play .au files using mpg321 on centos linux system
